/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/bweyl/Documents/PythonCoding/AdventOfCode/2018/Day2/nimcache/split.o /Users/bweyl/Documents/PythonCoding/AdventOfCode/2018/Day2/nimcache/split.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_DHIrxNKue9cYL0t8jxSKHqw tySequence_DHIrxNKue9cYL0t8jxSKHqw;
typedef struct tyTuple_g5PgxDE0xvxcVvCQbeddNg tyTuple_g5PgxDE0xvxcVvCQbeddNg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_g5PgxDE0xvxcVvCQbeddNg {
NIM_CHAR Field0;
NIM_CHAR Field1;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_DHIrxNKue9cYL0t8jxSKHqw {
  TGenericSeq Sup;
  tyTuple_g5PgxDE0xvxcVvCQbeddNg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_t9cVGQM6G9cVm9aODxxk9atdog_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitLines)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, sameLetters_pD7vv5jyDwsYhaEh1eC42g)(NimStringDesc* line1, NimStringDesc* line2);
N_LIB_PRIVATE N_NIMCALL(tySequence_DHIrxNKue9cYL0t8jxSKHqw*, zip_A8M9bfjc2VRV0BEJvvwI4rQ)(NIM_CHAR* s1, NI s1Len_0, NIM_CHAR* s2, NI s2Len_0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, second_wvUu8kPh62op6Rt7cXVP2g)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* input);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg)(NimStringDesc** s, NI sLen_0, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qsplit)(NI a, NI b);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, splitDatInit000)(void);
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* input_twKhH5UIqfAsnuJkYTCKCg;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_t9cVGQM6G9cVm9aODxxk9atdog_3, "/Users/bweyl/Documents/PythonCoding/AdventOfCode/2018/Day2/day2"
".in", 66);
STRING_LITERAL(TM_t9cVGQM6G9cVm9aODxxk9atdog_5, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, TM_t9cVGQM6G9cVm9aODxxk9atdog_2)(void) {
	nimGCvisit((void*)input_twKhH5UIqfAsnuJkYTCKCg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, sameLetters_pD7vv5jyDwsYhaEh1eC42g)(NimStringDesc* line1, NimStringDesc* line2) {
	NimStringDesc* result;
	nimfr_("sameLetters", "split.nim");
	result = (NimStringDesc*)0;
	{
		NIM_CHAR c1;
		NIM_CHAR c2;
		tySequence_DHIrxNKue9cYL0t8jxSKHqw* colontmp_;
		NI i;
		NI L;
		NI T2_;
		c1 = (NIM_CHAR)0;
		c2 = (NIM_CHAR)0;
		colontmp_ = (tySequence_DHIrxNKue9cYL0t8jxSKHqw*)0;
		nimln_(8, "split.nim");
		colontmp_ = zip_A8M9bfjc2VRV0BEJvvwI4rQ(line1->data, line1->Sup.len, line2->data, line2->Sup.len);
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_t9cVGQM6G9cVm9aODxxk9atdog_4;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				c1 = colontmp_->data[i].Field0;
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				c2 = colontmp_->data[i].Field1;
				nimln_(9, "split.nim");
				{
					if (!((NU8)(c1) == (NU8)(c2))) goto LA7_;
					nimln_(10, "split.nim");
					result = addChar(result, c1);
				}
				LA7_: ;
				nimln_(3809, "system.nim");
				TM_t9cVGQM6G9cVm9aODxxk9atdog_4 = addInt(i, ((NI) 1));
				i = (NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_4);
				nimln_(3810, "system.nim");
				{
					NI T11_;
					T11_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T11_ == L))) goto LA12_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_t9cVGQM6G9cVm9aODxxk9atdog_5));
				}
				LA12_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qsplit)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, second_wvUu8kPh62op6Rt7cXVP2g)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* input) {
	NimStringDesc* result;
	nimfr_("second", "split.nim");
{	result = (NimStringDesc*)0;
	{
		NI i;
		NimStringDesc* line1;
		NI i_2;
		i = (NI)0;
		line1 = (NimStringDesc*)0;
		nimln_(2285, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2286, "system.nim");
			while (1) {
				NI T4_;
				NI TM_t9cVGQM6G9cVm9aODxxk9atdog_10;
				T4_ = (input ? input->Sup.len : 0);
				if (!(i_2 < T4_)) goto LA3;
				nimln_(2287, "system.nim");
				i = i_2;
				if ((NU)(i_2) >= (NU)(input->Sup.len)) raiseIndexError();
				line1 = input->data[i_2];
				{
					NimStringDesc* line2;
					tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
					NI TM_t9cVGQM6G9cVm9aODxxk9atdog_6;
					NI T6_;
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T7_;
					NI i_3;
					NI L;
					NI T8_;
					line2 = (NimStringDesc*)0;
					colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
					nimln_(14, "split.nim");
					TM_t9cVGQM6G9cVm9aODxxk9atdog_6 = addInt(i, ((NI) 1));
					T6_ = (input ? (input->Sup.len-1) : -1);
					T7_ = dotdot__vDQySKWzgnxQdUarow6k5Qsplit((NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_6), T6_);
					colontmp_ = X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg(input->data, input->Sup.len, T7_);
					nimln_(3805, "system.nim");
					i_3 = ((NI) 0);
					nimln_(3806, "system.nim");
					T8_ = (colontmp_ ? colontmp_->Sup.len : 0);
					L = T8_;
					{
						nimln_(3807, "system.nim");
						while (1) {
							NI differences;
							NI TM_t9cVGQM6G9cVm9aODxxk9atdog_9;
							if (!(i_3 < L)) goto LA10;
							nimln_(3808, "system.nim");
							if ((NU)(i_3) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
							line2 = colontmp_->data[i_3];
							differences = (NI)0;
							{
								NIM_CHAR c1;
								NIM_CHAR c2;
								tySequence_DHIrxNKue9cYL0t8jxSKHqw* colontmp__2;
								NI i_4;
								NI L_2;
								NI T12_;
								c1 = (NIM_CHAR)0;
								c2 = (NIM_CHAR)0;
								colontmp__2 = (tySequence_DHIrxNKue9cYL0t8jxSKHqw*)0;
								nimln_(16, "split.nim");
								colontmp__2 = zip_A8M9bfjc2VRV0BEJvvwI4rQ(line1->data, line1->Sup.len, line2->data, line2->Sup.len);
								nimln_(3805, "system.nim");
								i_4 = ((NI) 0);
								nimln_(3806, "system.nim");
								T12_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
								L_2 = T12_;
								{
									nimln_(3807, "system.nim");
									while (1) {
										NI TM_t9cVGQM6G9cVm9aODxxk9atdog_8;
										if (!(i_4 < L_2)) goto LA14;
										nimln_(3808, "system.nim");
										if ((NU)(i_4) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
										c1 = colontmp__2->data[i_4].Field0;
										if ((NU)(i_4) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
										c2 = colontmp__2->data[i_4].Field1;
										nimln_(17, "split.nim");
										{
											NI TM_t9cVGQM6G9cVm9aODxxk9atdog_7;
											nimln_(398, "system.nim");
											nimln_(17, "split.nim");
											if (!!(((NU8)(c1) == (NU8)(c2)))) goto LA17_;
											nimln_(18, "split.nim");
											TM_t9cVGQM6G9cVm9aODxxk9atdog_7 = addInt(differences, ((NI) 1));
											differences = (NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_7);
										}
										LA17_: ;
										nimln_(3809, "system.nim");
										TM_t9cVGQM6G9cVm9aODxxk9atdog_8 = addInt(i_4, ((NI) 1));
										i_4 = (NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_8);
										nimln_(3810, "system.nim");
										{
											NI T21_;
											T21_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
											if (!!((T21_ == L_2))) goto LA22_;
											failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_t9cVGQM6G9cVm9aODxxk9atdog_5));
										}
										LA22_: ;
									} LA14: ;
								}
							}
							nimln_(19, "split.nim");
							{
								if (!(differences == ((NI) 1))) goto LA26_;
								nimln_(20, "split.nim");
								result = sameLetters_pD7vv5jyDwsYhaEh1eC42g(line1, line2);
								goto BeforeRet_;
							}
							LA26_: ;
							nimln_(3809, "system.nim");
							TM_t9cVGQM6G9cVm9aODxxk9atdog_9 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_9);
							nimln_(3810, "system.nim");
							{
								NI T30_;
								T30_ = (colontmp_ ? colontmp_->Sup.len : 0);
								if (!!((T30_ == L))) goto LA31_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_t9cVGQM6G9cVm9aODxxk9atdog_5));
							}
							LA31_: ;
						} LA10: ;
					}
				}
				nimln_(2288, "system.nim");
				TM_t9cVGQM6G9cVm9aODxxk9atdog_10 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_t9cVGQM6G9cVm9aODxxk9atdog_10);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	splitDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	nimfr_("split", "split.nim");
nimRegisterGlobalMarker(TM_t9cVGQM6G9cVm9aODxxk9atdog_2);
	nimln_(4, "split.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(((NimStringDesc*) &TM_t9cVGQM6G9cVm9aODxxk9atdog_3));
	asgnRefNoCycle((void**) (&input_twKhH5UIqfAsnuJkYTCKCg), nsuSplitLines(T1_));
	nimln_(22, "split.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = second_wvUu8kPh62op6Rt7cXVP2g(input_twKhH5UIqfAsnuJkYTCKCg);
	echoBinSafe(T2_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, splitDatInit000)(void) {
}

