/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/usr/local/Cellar/nim/0.18.0_1/nim/lib -o /Users/bweyl/Documents/PythonCoding/AdventOfCode/2018/Day1/nimcache/stdlib_intsets.o /Users/bweyl/Documents/PythonCoding/AdventOfCode/2018/Day1/nimcache/stdlib_intsets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ;
typedef struct tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg;
typedef struct tySequence_9brg1xNurxcus33lU4IE1Dw tySequence_9brg1xNurxcus33lU4IE1Dw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct TNimType TNimType;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI tyArray_emiAJ8okywrJw7ZHLzlXbQ[34];
struct tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg {
NI elems;
NI counter;
NI max;
tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* head;
tySequence_9brg1xNurxcus33lU4IE1Dw* data;
tyArray_emiAJ8okywrJw7ZHLzlXbQ a;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ {
tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_9brg1xNurxcus33lU4IE1Dw {
  TGenericSeq Sup;
  tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustRehash_taHuV1HJYdnKkjS6Tm5Tswintsets)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*, intSetGet_IcxbJfpUmsxePO8Fvv2aCg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, NI key);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, intSetRawInsert_I4xwTnLJbJwT2BPkb1SYSA)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, tySequence_9brg1xNurxcus33lU4IE1Dw** data, tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* desc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, intSetEnlarge_Ayv9chaeD5Za6gYR3XnnA3A)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_Vz0pPzxitckVclPPWiz0xw)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_9brg1xNurxcus33lU4IE1Dw)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*, intSetPut_0ZDJhLLWVElSxfwD0RRxbQ)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, NI key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_sYBLNwnPJlAFi0nfWU79awg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
static N_INLINE(void, bitincl_pcvkxvx474QnHLhgO0Dk9bAintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(void, incl_iUpE9bYmIR0fROyJskQwN8g)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(void, incl_k9c2x3iZPcRNZ01zMW30txQ)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* other);
N_LIB_PRIVATE N_NIMCALL(void, exclImpl_iUpE9bYmIR0fROyJskQwN8g_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(void, excl_iUpE9bYmIR0fROyJskQwN8g_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(void, excl_k9c2x3iZPcRNZ01zMW30txQ_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* other);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, missingOrExcl_B0EhVMrh5BBBZOOtYjAvVg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl_B0EhVMrh5BBBZOOtYjAvVg_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key);
N_LIB_PRIVATE N_NIMCALL(void, initIntSet_a9a80eJplB17xrdZJ41Baww)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, clear_lD4msJRzTJGFfA0rbiZqhg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* result);
static N_INLINE(NIM_BOOL, isNil_7atIZGZ28C4nVYigfGrZwgintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* x);
N_LIB_PRIVATE N_NIMCALL(void, assign_a2uuNOWD29cFDODAp4nip0A)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* dest, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* src);
N_LIB_PRIVATE N_NIMCALL(void, union_qTA3QWv9cJJZdlVDxLh9bEKA)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_LIB_PRIVATE N_NIMCALL(void, intersection_qTA3QWv9cJJZdlVDxLh9bEKA_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_LIB_PRIVATE N_NIMCALL(void, difference_qTA3QWv9cJJZdlVDxLh9bEKA_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_LIB_PRIVATE N_NIMCALL(void, symmetricDifference_qTA3QWv9cJJZdlVDxLh9bEKA_4)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
static N_INLINE(void, plus__IgZFkcU9bGmxoNvbk3A9awcgintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, star__IgZFkcU9bGmxoNvbk3A9awcg_2intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
static N_INLINE(void, minus__IgZFkcU9bGmxoNvbk3A9awcg_3intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, disjoint_JsWc9a7ThxfC0079chl72xSw)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2);
static N_INLINE(NI, len_r4gSK1eq0TkQLWSOY8DEAQintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s);
static N_INLINE(NI, card_r4gSK1eq0TkQLWSOY8DEAQ_2intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lteq__JsWc9a7ThxfC0079chl72xSw_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt__JsWc9a7ThxfC0079chl72xSw_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__JsWc9a7ThxfC0079chl72xSw_4)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__CV3c2hGxlfyxm3a5G0oCbw)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NIM_BOOL, empty_39bsv0yogVQhFyUP9bhXnyfwintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_ul49aWfv9aes8cutmeltT3gQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_9a8QARi5WsUggNU9bom7kzTQ_;
TNimType NTI_Vz0pPzxitckVclPPWiz0xw_;
TNimType NTI_9brg1xNurxcus33lU4IE1Dw_;
TNimType NTI_PQrmFm4BXFkFSVOUl1ojSg_;
TNimType NTI_emiAJ8okywrJw7ZHLzlXbQ_;
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_2, "\012counter < length ", 18);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_8, "\012not (data[h] == desc) ", 23);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_9, "data[h] == nil ", 15);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_18, "t.data[h] == nil ", 17);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_34, "dest.data[h] == nil ", 20);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_55, "{", 1);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_56, ", ", 2);
STRING_LITERAL(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_60, "}", 1);

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, mustRehash_taHuV1HJYdnKkjS6Tm5Tswintsets)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_3;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_4;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_5;
	nimfr_("mustRehash", "intsets.nim");
	result = (NIM_BOOL)0;
	nimln_(50, "intsets.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_2));
	}
	LA3_: ;
	nimln_(51, "intsets.nim");
	T5_ = (NIM_BOOL)0;
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_3 = mulInt(length, ((NI) 2));
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_3) < (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_4));
	if (T5_) goto LA6_;
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_5 = subInt(length, counter);
	T5_ = ((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets)(NI h, NI maxHash) {
	NI result;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_6;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_7;
	nimfr_("nextTry", "intsets.nim");
	result = (NI)0;
	nimln_(54, "intsets.nim");
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_6 = mulInt(((NI) 5), h);
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_7 = addInt((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_6), ((NI) 1));
	result = (NI)((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_7) & maxHash);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*, intSetGet_IcxbJfpUmsxePO8Fvv2aCg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, NI key) {
	tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* result;
	NI h;
	nimfr_("intSetGet", "intsets.nim");
{	result = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*)0;
	nimln_(57, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln_(58, "intsets.nim");
		while (1) {
			nimln_(398, "system.nim");
			nimln_(58, "intsets.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;
			nimln_(59, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				if (!((*(*t).data->data[h]).key == key)) goto LA5_;
				nimln_(60, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				result = (*t).data->data[h];
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(61, "intsets.nim");
			h = nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets(h, (*t).max);
		} LA2: ;
	}
	nimln_(62, "intsets.nim");
	result = NIM_NIL;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, intSetRawInsert_I4xwTnLJbJwT2BPkb1SYSA)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, tySequence_9brg1xNurxcus33lU4IE1Dw** data, tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* desc) {
	NI h;
	nimfr_("intSetRawInsert", "intsets.nim");
	nimln_(65, "intsets.nim");
	h = (NI)((*desc).key & (*t).max);
	{
		nimln_(66, "intsets.nim");
		while (1) {
			nimln_(398, "system.nim");
			nimln_(66, "intsets.nim");
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!(((*data)->data[h] == NIM_NIL))) goto LA2;
			nimln_(67, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
				if (!!(!(((*data)->data[h] == desc)))) goto LA5_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_8));
			}
			LA5_: ;
			nimln_(68, "intsets.nim");
			h = nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets(h, (*t).max);
		} LA2: ;
	}
	nimln_(69, "intsets.nim");
	{
		if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA9_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_9));
	}
	LA9_: ;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(70, "intsets.nim");
	asgnRef((void**) (&(*data)->data[h]), desc);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_Vz0pPzxitckVclPPWiz0xw)(void* p, NI op) {
	tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* a;
	NI T1_;
	a = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*)p;
	nimGCvisit((void*)(*a).next, op);
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence_9brg1xNurxcus33lU4IE1Dw)(void* p, NI op) {
	tySequence_9brg1xNurxcus33lU4IE1Dw* a;
	NI T1_;
	a = (tySequence_9brg1xNurxcus33lU4IE1Dw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, intSetEnlarge_Ayv9chaeD5Za6gYR3XnnA3A)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t) {
	tySequence_9brg1xNurxcus33lU4IE1Dw* n;
	NI oldMax;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_10;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_11;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_12;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_13;
	tySequence_9brg1xNurxcus33lU4IE1Dw* T8_;
	nimfr_("intSetEnlarge", "intsets.nim");
	n = (tySequence_9brg1xNurxcus33lU4IE1Dw*)0;
	nimln_(74, "intsets.nim");
	oldMax = (*t).max;
	nimln_(75, "intsets.nim");
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_10 = addInt((*t).max, ((NI) 1));
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_11 = mulInt((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_10), ((NI) 2));
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_12 = subInt((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_11), ((NI) 1));
	(*t).max = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_12);
	nimln_(76, "intsets.nim");
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_13 = addInt((*t).max, ((NI) 1));
	n = (tySequence_9brg1xNurxcus33lU4IE1Dw*) newSeq((&NTI_9brg1xNurxcus33lU4IE1Dw_), ((NI)chckRange((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_13), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_15;
				if (!(res <= oldMax)) goto LA3;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(78, "intsets.nim");
				{
					nimln_(398, "system.nim");
					nimln_(78, "intsets.nim");
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!!(((*t).data->data[i] == NIM_NIL))) goto LA6_;
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					intSetRawInsert_I4xwTnLJbJwT2BPkb1SYSA((&(*t)), (&n), (*t).data->data[i]);
				}
				LA6_: ;
				nimln_(2035, "system.nim");
				TM_ulJ2WYumkJwZ9b5Ewe7sCpg_15 = addInt(res, ((NI) 1));
				res = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_15);
			} LA3: ;
		}
	}
	nimln_(79, "intsets.nim");
	T8_ = (tySequence_9brg1xNurxcus33lU4IE1Dw*)0;
	T8_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T8_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*, intSetPut_0ZDJhLLWVElSxfwD0RRxbQ)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* t, NI key) {
	tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* result;
	NI h;
	NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_17;
	nimfr_("intSetPut", "intsets.nim");
{	result = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*)0;
	nimln_(82, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln_(83, "intsets.nim");
		while (1) {
			nimln_(398, "system.nim");
			nimln_(83, "intsets.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;
			nimln_(84, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				if (!((*(*t).data->data[h]).key == key)) goto LA5_;
				nimln_(85, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				result = (*t).data->data[h];
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(86, "intsets.nim");
			h = nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets(h, (*t).max);
		} LA2: ;
	}
	nimln_(87, "intsets.nim");
	{
		NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_16;
		NIM_BOOL T9_;
		TM_ulJ2WYumkJwZ9b5Ewe7sCpg_16 = addInt((*t).max, ((NI) 1));
		T9_ = (NIM_BOOL)0;
		T9_ = mustRehash_taHuV1HJYdnKkjS6Tm5Tswintsets((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_16), (*t).counter);
		if (!T9_) goto LA10_;
		intSetEnlarge_Ayv9chaeD5Za6gYR3XnnA3A(t);
	}
	LA10_: ;
	nimln_(88, "intsets.nim");
	TM_ulJ2WYumkJwZ9b5Ewe7sCpg_17 = addInt((*t).counter, ((NI) 1));
	(*t).counter = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_17);
	nimln_(89, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln_(90, "intsets.nim");
		while (1) {
			nimln_(398, "system.nim");
			nimln_(90, "intsets.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA13;
			h = nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets(h, (*t).max);
		} LA13: ;
	}
	nimln_(91, "intsets.nim");
	{
		if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		if (!!(((*t).data->data[h] == NIM_NIL))) goto LA16_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_18));
	}
	LA16_: ;
	nimln_(92, "intsets.nim");
	result = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*) newObj((&NTI_Vz0pPzxitckVclPPWiz0xw_), sizeof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ));
	nimln_(93, "intsets.nim");
	asgnRef((void**) (&(*result).next), (*t).head);
	nimln_(94, "intsets.nim");
	(*result).key = key;
	nimln_(95, "intsets.nim");
	unsureAsgnRef((void**) (&(*t).head), result);
	if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
	nimln_(96, "intsets.nim");
	asgnRef((void**) (&(*t).data->data[h]), result);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_sYBLNwnPJlAFi0nfWU79awg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	NIM_BOOL result;
	nimfr_("contains", "intsets.nim");
{	result = (NIM_BOOL)0;
	nimln_(100, "intsets.nim");
	{
		if (!((*s).elems <= ((NI) 34))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(101, "intsets.nim");
			colontmp_ = (*s).elems;
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_19;
					if (!(i_2 < colontmp_)) goto LA7;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(102, "intsets.nim");
					{
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						if (!((*s).a[(i)- 0] == key)) goto LA10_;
						result = NIM_TRUE;
						goto BeforeRet_;
					}
					LA10_: ;
					nimln_(3522, "system.nim");
					TM_ulJ2WYumkJwZ9b5Ewe7sCpg_19 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_19);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* t;
		nimln_(104, "intsets.nim");
		t = intSetGet_IcxbJfpUmsxePO8Fvv2aCg(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
		nimln_(105, "intsets.nim");
		{
			NI u;
			nimln_(398, "system.nim");
			nimln_(105, "intsets.nim");
			if (!!((t == NIM_NIL))) goto LA15_;
			nimln_(106, "intsets.nim");
			u = (NI)(key & ((NI) 511));
			nimln_(107, "intsets.nim");
			nimln_(398, "system.nim");
			nimln_(107, "intsets.nim");
			if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			result = !(((NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)((NI)(u & ((NI) 63))))) == ((NI) 0)));
		}
		goto LA13_;
		LA15_: ;
		{
			nimln_(109, "intsets.nim");
			result = NIM_FALSE;
		}
		LA13_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, bitincl_pcvkxvx474QnHLhgO0Dk9bAintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* t;
	NI u;
	nimfr_("bitincl", "intsets.nim");
	nimln_(134, "intsets.nim");
	t = intSetPut_0ZDJhLLWVElSxfwD0RRxbQ(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	nimln_(135, "intsets.nim");
	u = (NI)(key & ((NI) 511));
	nimln_(136, "intsets.nim");
	if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
	if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
	nimln_(137, "intsets.nim");
	(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)((NI)(u & ((NI) 63)))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_iUpE9bYmIR0fROyJskQwN8g)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	nimfr_("incl", "intsets.nim");
{	nimln_(141, "intsets.nim");
	{
		if (!((*s).elems <= ((NI) 34))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(142, "intsets.nim");
			colontmp_ = (*s).elems;
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_20;
					if (!(i_2 < colontmp_)) goto LA7;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(143, "intsets.nim");
					{
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						if (!((*s).a[(i)- 0] == key)) goto LA10_;
						goto BeforeRet_;
					}
					LA10_: ;
					nimln_(3522, "system.nim");
					TM_ulJ2WYumkJwZ9b5Ewe7sCpg_20 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_20);
				} LA7: ;
			}
		}
		nimln_(144, "intsets.nim");
		{
			NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_21;
			if (!((*s).elems < ((NI) 34))) goto LA14_;
			if ((NU)((*s).elems) > (NU)(33)) raiseIndexError();
			nimln_(145, "intsets.nim");
			(*s).a[((*s).elems)- 0] = key;
			nimln_(146, "intsets.nim");
			TM_ulJ2WYumkJwZ9b5Ewe7sCpg_21 = addInt((*s).elems, ((NI) 1));
			(*s).elems = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_21);
			nimln_(147, "intsets.nim");
			goto BeforeRet_;
		}
		LA14_: ;
		nimln_(148, "intsets.nim");
		unsureAsgnRef((void**) (&(*s).data), (tySequence_9brg1xNurxcus33lU4IE1Dw*) newSeq((&NTI_9brg1xNurxcus33lU4IE1Dw_), ((NI) 8)));
		nimln_(149, "intsets.nim");
		(*s).max = ((NI) 7);
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(150, "intsets.nim");
			colontmp__2 = (*s).elems;
			nimln_(3519, "system.nim");
			i_4 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_22;
					if (!(i_4 < colontmp__2)) goto LA18;
					nimln_(3521, "system.nim");
					i_3 = i_4;
					nimln_(151, "intsets.nim");
					if ((NU)(i_3) > (NU)(33)) raiseIndexError();
					bitincl_pcvkxvx474QnHLhgO0Dk9bAintsets(s, (*s).a[(i_3)- 0]);
					nimln_(3522, "system.nim");
					TM_ulJ2WYumkJwZ9b5Ewe7sCpg_22 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_22);
				} LA18: ;
			}
		}
		nimln_(152, "intsets.nim");
		(*s).elems = ((NI) 35);
	}
	LA3_: ;
	nimln_(154, "intsets.nim");
	bitincl_pcvkxvx474QnHLhgO0Dk9bAintsets(s, key);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, incl_k9c2x3iZPcRNZ01zMW30txQ)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* other) {
	nimfr_("incl", "intsets.nim");
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*other).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*other).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_23;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*other).a[(i)- 0];
						nimln_(158, "intsets.nim");
						incl_iUpE9bYmIR0fROyJskQwN8g(s, item);
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_23 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_23);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*other).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA11;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_25;
							if (!(i_3 <= ((NI) 7))) goto LA13;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_24;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA15;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA18_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(158, "intsets.nim");
										incl_iUpE9bYmIR0fROyJskQwN8g(s, item);
									}
									LA18_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_24 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_24);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA15: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_25 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_25);
						} LA13: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA11: ;
			}
		}
		LA2_: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, exclImpl_iUpE9bYmIR0fROyJskQwN8g_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	nimfr_("exclImpl", "intsets.nim");
{	nimln_(161, "intsets.nim");
	{
		if (!((*s).elems <= ((NI) 34))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(162, "intsets.nim");
			colontmp_ = (*s).elems;
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_28;
					if (!(i_2 < colontmp_)) goto LA7;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(163, "intsets.nim");
					{
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_26;
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_27;
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						if (!((*s).a[(i)- 0] == key)) goto LA10_;
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						nimln_(164, "intsets.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_26 = subInt((*s).elems, ((NI) 1));
						if ((NU)((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_26)) > (NU)(33)) raiseIndexError();
						(*s).a[(i)- 0] = (*s).a[((NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_26))- 0];
						nimln_(165, "intsets.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_27 = subInt((*s).elems, ((NI) 1));
						(*s).elems = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_27);
						nimln_(166, "intsets.nim");
						goto BeforeRet_;
					}
					LA10_: ;
					nimln_(3522, "system.nim");
					TM_ulJ2WYumkJwZ9b5Ewe7sCpg_28 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_28);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* t;
		nimln_(168, "intsets.nim");
		t = intSetGet_IcxbJfpUmsxePO8Fvv2aCg((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
		nimln_(169, "intsets.nim");
		{
			NI u;
			nimln_(398, "system.nim");
			nimln_(169, "intsets.nim");
			if (!!((t == NIM_NIL))) goto LA15_;
			nimln_(170, "intsets.nim");
			u = (NI)(key & ((NI) 511));
			nimln_(171, "intsets.nim");
			if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			nimln_(172, "intsets.nim");
			(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)((NI)(u & ((NI) 63)))))));
		}
		LA15_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, excl_iUpE9bYmIR0fROyJskQwN8g_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	nimfr_("excl", "intsets.nim");
	nimln_(176, "intsets.nim");
	exclImpl_iUpE9bYmIR0fROyJskQwN8g_2(s, key);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, excl_k9c2x3iZPcRNZ01zMW30txQ_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* other) {
	nimfr_("excl", "intsets.nim");
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*other).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*other).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_29;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*other).a[(i)- 0];
						nimln_(180, "intsets.nim");
						excl_iUpE9bYmIR0fROyJskQwN8g_3(s, item);
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_29 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_29);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*other).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA11;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_31;
							if (!(i_3 <= ((NI) 7))) goto LA13;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_30;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA15;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA18_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(180, "intsets.nim");
										excl_iUpE9bYmIR0fROyJskQwN8g_3(s, item);
									}
									LA18_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_30 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_30);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA15: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_31 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_31);
						} LA13: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA11: ;
			}
		}
		LA2_: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, missingOrExcl_B0EhVMrh5BBBZOOtYjAvVg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	NIM_BOOL result;
	NI count;
	nimfr_("missingOrExcl", "intsets.nim");
	result = (NIM_BOOL)0;
	nimln_(185, "intsets.nim");
	count = (*s).elems;
	nimln_(186, "intsets.nim");
	exclImpl_iUpE9bYmIR0fROyJskQwN8g_2(s, key);
	nimln_(187, "intsets.nim");
	result = (count == (*s).elems);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl_B0EhVMrh5BBBZOOtYjAvVg_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s, NI key) {
	NIM_BOOL result;
	nimfr_("containsOrIncl", "intsets.nim");
{	result = (NIM_BOOL)0;
	nimln_(192, "intsets.nim");
	{
		if (!((*s).elems <= ((NI) 34))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(193, "intsets.nim");
			colontmp_ = (*s).elems;
			nimln_(3519, "system.nim");
			i_2 = ((NI) 0);
			{
				nimln_(3520, "system.nim");
				while (1) {
					NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_32;
					if (!(i_2 < colontmp_)) goto LA7;
					nimln_(3521, "system.nim");
					i = i_2;
					nimln_(194, "intsets.nim");
					{
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						if (!((*s).a[(i)- 0] == key)) goto LA10_;
						nimln_(195, "intsets.nim");
						result = NIM_TRUE;
						goto BeforeRet_;
					}
					LA10_: ;
					nimln_(3522, "system.nim");
					TM_ulJ2WYumkJwZ9b5Ewe7sCpg_32 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_32);
				} LA7: ;
			}
		}
		nimln_(196, "intsets.nim");
		incl_iUpE9bYmIR0fROyJskQwN8g(s, key);
		nimln_(197, "intsets.nim");
		result = NIM_FALSE;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* t;
		nimln_(199, "intsets.nim");
		t = intSetGet_IcxbJfpUmsxePO8Fvv2aCg((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
		nimln_(200, "intsets.nim");
		{
			NI u;
			nimln_(398, "system.nim");
			nimln_(200, "intsets.nim");
			if (!!((t == NIM_NIL))) goto LA15_;
			nimln_(201, "intsets.nim");
			u = (NI)(key & ((NI) 511));
			nimln_(202, "intsets.nim");
			nimln_(398, "system.nim");
			nimln_(202, "intsets.nim");
			if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			result = !(((NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)((NI)(u & ((NI) 63))))) == ((NI) 0)));
			nimln_(203, "intsets.nim");
			{
				if (!!(result)) goto LA19_;
				nimln_(204, "intsets.nim");
				if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
				if ((NU)((NI)((NU64)(u) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
				nimln_(205, "intsets.nim");
				(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)((NI)(u & ((NI) 63)))));
			}
			LA19_: ;
		}
		goto LA13_;
		LA15_: ;
		{
			nimln_(207, "intsets.nim");
			incl_iUpE9bYmIR0fROyJskQwN8g(s, key);
			nimln_(208, "intsets.nim");
			result = NIM_FALSE;
		}
		LA13_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initIntSet_a9a80eJplB17xrdZJ41Baww)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	nimfr_("initIntSet", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(215, "intsets.nim");
	genericSeqAssign((&(*Result).data), NIM_NIL, (&NTI_9brg1xNurxcus33lU4IE1Dw_));
	nimln_(216, "intsets.nim");
	(*Result).max = ((NI) 0);
	nimln_(217, "intsets.nim");
	(*Result).counter = ((NI) 0);
	nimln_(218, "intsets.nim");
	unsureAsgnRef((void**) (&(*Result).head), NIM_NIL);
	nimln_(219, "intsets.nim");
	(*Result).elems = ((NI) 0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, clear_lD4msJRzTJGFfA0rbiZqhg)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* result) {
	nimfr_("clear", "intsets.nim");
	nimln_(225, "intsets.nim");
	genericSeqAssign((&(*result).data), NIM_NIL, (&NTI_9brg1xNurxcus33lU4IE1Dw_));
	nimln_(226, "intsets.nim");
	(*result).max = ((NI) 0);
	nimln_(227, "intsets.nim");
	(*result).counter = ((NI) 0);
	nimln_(228, "intsets.nim");
	unsureAsgnRef((void**) (&(*result).head), NIM_NIL);
	nimln_(229, "intsets.nim");
	(*result).elems = ((NI) 0);
	popFrame();
}

static N_INLINE(NIM_BOOL, isNil_7atIZGZ28C4nVYigfGrZwgintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* x) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isNil", "intsets.nim");
	result = (NIM_BOOL)0;
	nimln_(231, "intsets.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((*x).head == 0);
	if (!(T1_)) goto LA2_;
	T1_ = ((*x).elems == ((NI) 0));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, assign_a2uuNOWD29cFDODAp4nip0A)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* dest, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* src) {
	nimfr_("assign", "intsets.nim");
	nimln_(236, "intsets.nim");
	{
		if (!((*src).elems <= ((NI) 34))) goto LA3_;
		nimln_(237, "intsets.nim");
		genericSeqAssign((&(*dest).data), NIM_NIL, (&NTI_9brg1xNurxcus33lU4IE1Dw_));
		nimln_(238, "intsets.nim");
		(*dest).max = ((NI) 0);
		nimln_(239, "intsets.nim");
		(*dest).counter = (*src).counter;
		nimln_(240, "intsets.nim");
		unsureAsgnRef((void**) (&(*dest).head), NIM_NIL);
		nimln_(241, "intsets.nim");
		(*dest).elems = (*src).elems;
		nimln_(242, "intsets.nim");
		memcpy((void*)(*dest).a, (NIM_CONST void*)(*src).a, sizeof(tyArray_emiAJ8okywrJw7ZHLzlXbQ));
	}
	goto LA1_;
	LA3_: ;
	{
		NI T6_;
		tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* it;
		nimln_(244, "intsets.nim");
		(*dest).counter = (*src).counter;
		nimln_(245, "intsets.nim");
		(*dest).max = (*src).max;
		nimln_(246, "intsets.nim");
		T6_ = ((*src).data ? (*src).data->Sup.len : 0);
		unsureAsgnRef((void**) (&(*dest).data), (tySequence_9brg1xNurxcus33lU4IE1Dw*) newSeq((&NTI_9brg1xNurxcus33lU4IE1Dw_), ((NI)chckRange(T6_, ((NI) 0), ((NI) IL64(9223372036854775807))))));
		nimln_(248, "intsets.nim");
		it = (*src).head;
		{
			nimln_(249, "intsets.nim");
			while (1) {
				NI h;
				tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* n;
				nimln_(398, "system.nim");
				nimln_(249, "intsets.nim");
				if (!!((it == NIM_NIL))) goto LA8;
				nimln_(251, "intsets.nim");
				h = (NI)((*it).key & (*dest).max);
				{
					nimln_(252, "intsets.nim");
					while (1) {
						nimln_(398, "system.nim");
						nimln_(252, "intsets.nim");
						if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
						if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA10;
						h = nextTry_Tx9c0j9b5WTbCx0lfW5eXjQgintsets(h, (*dest).max);
					} LA10: ;
				}
				nimln_(253, "intsets.nim");
				{
					if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
					if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_34));
				}
				LA13_: ;
				n = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*)0;
				nimln_(256, "intsets.nim");
				n = (tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*) newObj((&NTI_Vz0pPzxitckVclPPWiz0xw_), sizeof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ));
				nimln_(257, "intsets.nim");
				asgnRef((void**) (&(*n).next), (*dest).head);
				nimln_(258, "intsets.nim");
				(*n).key = (*it).key;
				nimln_(259, "intsets.nim");
				memcpy((void*)(*n).bits, (NIM_CONST void*)(*it).bits, sizeof(tyArray_9a8QARi5WsUggNU9bom7kzTQ));
				nimln_(260, "intsets.nim");
				unsureAsgnRef((void**) (&(*dest).head), n);
				if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
				nimln_(261, "intsets.nim");
				asgnRef((void**) (&(*dest).data->data[h]), n);
				nimln_(263, "intsets.nim");
				it = (*it).next;
			} LA8: ;
		}
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, union_qTA3QWv9cJJZdlVDxLh9bEKA)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	nimfr_("union", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(267, "intsets.nim");
	assign_a2uuNOWD29cFDODAp4nip0A(Result, s1);
	nimln_(268, "intsets.nim");
	incl_k9c2x3iZPcRNZ01zMW30txQ(Result, s2);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, intersection_qTA3QWv9cJJZdlVDxLh9bEKA_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	nimfr_("intersection", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(272, "intsets.nim");
	initIntSet_a9a80eJplB17xrdZJ41Baww(Result);
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s1).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s1).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_35;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*s1).a[(i)- 0];
						nimln_(274, "intsets.nim");
						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
							if (!T11_) goto LA12_;
							nimln_(275, "intsets.nim");
							incl_iUpE9bYmIR0fROyJskQwN8g(Result, item);
						}
						LA12_: ;
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_35 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_35);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s1).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_37;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_36;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(274, "intsets.nim");
										{
											NIM_BOOL T27_;
											T27_ = (NIM_BOOL)0;
											T27_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
											if (!T27_) goto LA28_;
											nimln_(275, "intsets.nim");
											incl_iUpE9bYmIR0fROyJskQwN8g(Result, item);
										}
										LA28_: ;
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_36 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_36);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_37 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_37);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, difference_qTA3QWv9cJJZdlVDxLh9bEKA_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	nimfr_("difference", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(279, "intsets.nim");
	initIntSet_a9a80eJplB17xrdZJ41Baww(Result);
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s1).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s1).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_38;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*s1).a[(i)- 0];
						nimln_(281, "intsets.nim");
						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
							if (!!(T11_)) goto LA12_;
							nimln_(282, "intsets.nim");
							incl_iUpE9bYmIR0fROyJskQwN8g(Result, item);
						}
						LA12_: ;
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_38 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_38);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s1).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_40;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_39;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(281, "intsets.nim");
										{
											NIM_BOOL T27_;
											T27_ = (NIM_BOOL)0;
											T27_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
											if (!!(T27_)) goto LA28_;
											nimln_(282, "intsets.nim");
											incl_iUpE9bYmIR0fROyJskQwN8g(Result, item);
										}
										LA28_: ;
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_39 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_39);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_40 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_40);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, symmetricDifference_qTA3QWv9cJJZdlVDxLh9bEKA_4)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	nimfr_("symmetricDifference", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(286, "intsets.nim");
	assign_a2uuNOWD29cFDODAp4nip0A(Result, s1);
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s2).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s2).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_41;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*s2).a[(i)- 0];
						nimln_(288, "intsets.nim");
						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = containsOrIncl_B0EhVMrh5BBBZOOtYjAvVg_2(Result, item);
							if (!T11_) goto LA12_;
							excl_iUpE9bYmIR0fROyJskQwN8g_3(Result, item);
						}
						LA12_: ;
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_41 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_41);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s2).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_43;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_42;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(288, "intsets.nim");
										{
											NIM_BOOL T27_;
											T27_ = (NIM_BOOL)0;
											T27_ = containsOrIncl_B0EhVMrh5BBBZOOtYjAvVg_2(Result, item);
											if (!T27_) goto LA28_;
											excl_iUpE9bYmIR0fROyJskQwN8g_3(Result, item);
										}
										LA28_: ;
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_42 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_42);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_43 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_43);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	popFrame();
}

static N_INLINE(void, plus__IgZFkcU9bGmxoNvbk3A9awcgintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg T1_;
	nimfr_("+", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(292, "intsets.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	union_qTA3QWv9cJJZdlVDxLh9bEKA(s1, s2, (&T1_));
	genericShallowAssign((void*)Result, (void*)(&T1_), (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	popFrame();
}

static N_INLINE(void, star__IgZFkcU9bGmxoNvbk3A9awcg_2intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg T1_;
	nimfr_("*", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(296, "intsets.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	intersection_qTA3QWv9cJJZdlVDxLh9bEKA_2(s1, s2, (&T1_));
	genericShallowAssign((void*)Result, (void*)(&T1_), (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	popFrame();
}

static N_INLINE(void, minus__IgZFkcU9bGmxoNvbk3A9awcg_3intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* Result) {
	tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg T1_;
	nimfr_("-", "intsets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	nimln_(300, "intsets.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	difference_qTA3QWv9cJJZdlVDxLh9bEKA_3(s1, s2, (&T1_));
	genericShallowAssign((void*)Result, (void*)(&T1_), (&NTI_PQrmFm4BXFkFSVOUl1ojSg_));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, disjoint_JsWc9a7ThxfC0079chl72xSw)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2) {
	NIM_BOOL result;
	nimfr_("disjoint", "intsets.nim");
{	result = (NIM_BOOL)0;
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s1).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s1).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_44;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*s1).a[(i)- 0];
						nimln_(305, "intsets.nim");
						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
							if (!T11_) goto LA12_;
							nimln_(306, "intsets.nim");
							result = NIM_FALSE;
							goto BeforeRet_;
						}
						LA12_: ;
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_44 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_44);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s1).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_46;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_45;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(305, "intsets.nim");
										{
											NIM_BOOL T27_;
											T27_ = (NIM_BOOL)0;
											T27_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
											if (!T27_) goto LA28_;
											nimln_(306, "intsets.nim");
											result = NIM_FALSE;
											goto BeforeRet_;
										}
										LA28_: ;
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_45 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_45);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_46 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_46);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	nimln_(307, "intsets.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, len_r4gSK1eq0TkQLWSOY8DEAQintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s) {
	NI result;
	nimfr_("len", "intsets.nim");
	result = (NI)0;
	nimln_(311, "intsets.nim");
	{
		if (!((*s).elems < ((NI) 34))) goto LA3_;
		nimln_(312, "intsets.nim");
		result = (*s).elems;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(314, "intsets.nim");
		result = ((NI) 0);
		{
			NI _;
			_ = (NI)0;
			nimln_(113, "intsets.nim");
			{
				if (!((*s).elems <= ((NI) 34))) goto LA9_;
				{
					NI i;
					NI colontmp_;
					NI i_2;
					i = (NI)0;
					colontmp_ = (NI)0;
					nimln_(114, "intsets.nim");
					colontmp_ = (*s).elems;
					nimln_(3519, "system.nim");
					i_2 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_47;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_48;
							if (!(i_2 < colontmp_)) goto LA13;
							nimln_(3521, "system.nim");
							i = i_2;
							nimln_(115, "intsets.nim");
							if ((NU)(i) > (NU)(33)) raiseIndexError();
							_ = (*s).a[(i)- 0];
							nimln_(316, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_47 = addInt(result, ((NI) 1));
							result = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_47);
							nimln_(3522, "system.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_48 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_48);
						} LA13: ;
					}
				}
			}
			goto LA7_;
			LA9_: ;
			{
				tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
				nimln_(117, "intsets.nim");
				r = (*s).head;
				{
					nimln_(118, "intsets.nim");
					while (1) {
						NI i_3;
						nimln_(398, "system.nim");
						nimln_(118, "intsets.nim");
						if (!!((r == NIM_NIL))) goto LA16;
						nimln_(119, "intsets.nim");
						i_3 = ((NI) 0);
						{
							nimln_(120, "intsets.nim");
							while (1) {
								NI w;
								NI j;
								NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_51;
								if (!(i_3 <= ((NI) 7))) goto LA18;
								nimln_(121, "intsets.nim");
								if ((NU)(i_3) > (NU)(7)) raiseIndexError();
								w = (*r).bits[(i_3)- 0];
								nimln_(124, "intsets.nim");
								j = ((NI) 0);
								{
									nimln_(125, "intsets.nim");
									while (1) {
										NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_50;
										nimln_(398, "system.nim");
										nimln_(125, "intsets.nim");
										if (!!((w == ((NI) 0)))) goto LA20;
										nimln_(126, "intsets.nim");
										{
											NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_49;
											nimln_(398, "system.nim");
											nimln_(126, "intsets.nim");
											if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
											nimln_(127, "intsets.nim");
											_ = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
											nimln_(316, "intsets.nim");
											TM_ulJ2WYumkJwZ9b5Ewe7sCpg_49 = addInt(result, ((NI) 1));
											result = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_49);
										}
										LA23_: ;
										nimln_(128, "intsets.nim");
										TM_ulJ2WYumkJwZ9b5Ewe7sCpg_50 = addInt(j, ((NI) 1));
										j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_50);
										nimln_(129, "intsets.nim");
										w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
									} LA20: ;
								}
								nimln_(130, "intsets.nim");
								TM_ulJ2WYumkJwZ9b5Ewe7sCpg_51 = addInt(i_3, ((NI) 1));
								i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_51);
							} LA18: ;
						}
						nimln_(131, "intsets.nim");
						r = (*r).next;
					} LA16: ;
				}
			}
			LA7_: ;
		}
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, card_r4gSK1eq0TkQLWSOY8DEAQ_2intsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s) {
	NI result;
	nimfr_("card", "intsets.nim");
	result = (NI)0;
	nimln_(320, "intsets.nim");
	result = len_r4gSK1eq0TkQLWSOY8DEAQintsets(s);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lteq__JsWc9a7ThxfC0079chl72xSw_2)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2) {
	NIM_BOOL result;
	nimfr_("<=", "intsets.nim");
{	result = (NIM_BOOL)0;
	{
		NI item;
		item = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s1).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s1).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_52;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						item = (*s1).a[(i)- 0];
						nimln_(325, "intsets.nim");
						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
							if (!!(T11_)) goto LA12_;
							nimln_(326, "intsets.nim");
							result = NIM_FALSE;
							goto BeforeRet_;
						}
						LA12_: ;
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_52 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_52);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s1).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_54;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_53;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										item = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(325, "intsets.nim");
										{
											NIM_BOOL T27_;
											T27_ = (NIM_BOOL)0;
											T27_ = contains_sYBLNwnPJlAFi0nfWU79awg(s2, item);
											if (!!(T27_)) goto LA28_;
											nimln_(326, "intsets.nim");
											result = NIM_FALSE;
											goto BeforeRet_;
										}
										LA28_: ;
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_53 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_53);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_54 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_54);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	nimln_(327, "intsets.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt__JsWc9a7ThxfC0079chl72xSw_3)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	nimfr_("<", "intsets.nim");
{	result = (NIM_BOOL)0;
	nimln_(331, "intsets.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = lteq__JsWc9a7ThxfC0079chl72xSw_2(s1, s2);
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	T3_ = lteq__JsWc9a7ThxfC0079chl72xSw_2(s2, s1);
	T1_ = !(T3_);
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__JsWc9a7ThxfC0079chl72xSw_4)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s1, tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("==", "intsets.nim");
{	result = (NIM_BOOL)0;
	nimln_(335, "intsets.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = lteq__JsWc9a7ThxfC0079chl72xSw_2(s1, s2);
	if (!(T1_)) goto LA2_;
	T1_ = lteq__JsWc9a7ThxfC0079chl72xSw_2(s2, s1);
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__CV3c2hGxlfyxm3a5G0oCbw)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s) {
	NimStringDesc* result;
	nimfr_("$", "intsets.nim");
	result = (NimStringDesc*)0;
	nimln_(338, "intsets.nim");
	result = copyString(((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_55));
	{
		NI key;
		key = (NI)0;
		nimln_(113, "intsets.nim");
		{
			if (!((*s).elems <= ((NI) 34))) goto LA4_;
			{
				NI i;
				NI colontmp_;
				NI i_2;
				i = (NI)0;
				colontmp_ = (NI)0;
				nimln_(114, "intsets.nim");
				colontmp_ = (*s).elems;
				nimln_(3519, "system.nim");
				i_2 = ((NI) 0);
				{
					nimln_(3520, "system.nim");
					while (1) {
						NimStringDesc* T13_;
						NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_57;
						if (!(i_2 < colontmp_)) goto LA8;
						nimln_(3521, "system.nim");
						i = i_2;
						nimln_(115, "intsets.nim");
						if ((NU)(i) > (NU)(33)) raiseIndexError();
						key = (*s).a[(i)- 0];
						nimln_(340, "intsets.nim");
						{
							if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA11_;
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_56));
						}
						LA11_: ;
						nimln_(341, "intsets.nim");
						T13_ = (NimStringDesc*)0;
						T13_ = nimIntToStr(key);
						result = resizeString(result, T13_->Sup.len + 0);
appendString(result, T13_);
						nimln_(3522, "system.nim");
						TM_ulJ2WYumkJwZ9b5Ewe7sCpg_57 = addInt(i_2, ((NI) 1));
						i_2 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_57);
					} LA8: ;
				}
			}
		}
		goto LA2_;
		LA4_: ;
		{
			tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ* r;
			nimln_(117, "intsets.nim");
			r = (*s).head;
			{
				nimln_(118, "intsets.nim");
				while (1) {
					NI i_3;
					nimln_(398, "system.nim");
					nimln_(118, "intsets.nim");
					if (!!((r == NIM_NIL))) goto LA16;
					nimln_(119, "intsets.nim");
					i_3 = ((NI) 0);
					{
						nimln_(120, "intsets.nim");
						while (1) {
							NI w;
							NI j;
							NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_59;
							if (!(i_3 <= ((NI) 7))) goto LA18;
							nimln_(121, "intsets.nim");
							if ((NU)(i_3) > (NU)(7)) raiseIndexError();
							w = (*r).bits[(i_3)- 0];
							nimln_(124, "intsets.nim");
							j = ((NI) 0);
							{
								nimln_(125, "intsets.nim");
								while (1) {
									NI TM_ulJ2WYumkJwZ9b5Ewe7sCpg_58;
									nimln_(398, "system.nim");
									nimln_(125, "intsets.nim");
									if (!!((w == ((NI) 0)))) goto LA20;
									nimln_(126, "intsets.nim");
									{
										NimStringDesc* T29_;
										nimln_(398, "system.nim");
										nimln_(126, "intsets.nim");
										if (!!(((NI)(w & ((NI) 1)) == ((NI) 0)))) goto LA23_;
										nimln_(127, "intsets.nim");
										key = (NI)((NI)((NU64)((*r).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_3) << (NU64)(((NI) 6)))) + (NU64)(j)));
										nimln_(340, "intsets.nim");
										{
											if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA27_;
											result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_56));
										}
										LA27_: ;
										nimln_(341, "intsets.nim");
										T29_ = (NimStringDesc*)0;
										T29_ = nimIntToStr(key);
										result = resizeString(result, T29_->Sup.len + 0);
appendString(result, T29_);
									}
									LA23_: ;
									nimln_(128, "intsets.nim");
									TM_ulJ2WYumkJwZ9b5Ewe7sCpg_58 = addInt(j, ((NI) 1));
									j = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_58);
									nimln_(129, "intsets.nim");
									w = (NI)((NU64)(w) >> (NU64)(((NI) 1)));
								} LA20: ;
							}
							nimln_(130, "intsets.nim");
							TM_ulJ2WYumkJwZ9b5Ewe7sCpg_59 = addInt(i_3, ((NI) 1));
							i_3 = (NI)(TM_ulJ2WYumkJwZ9b5Ewe7sCpg_59);
						} LA18: ;
					}
					nimln_(131, "intsets.nim");
					r = (*r).next;
				} LA16: ;
			}
		}
		LA2_: ;
	}
	nimln_(342, "intsets.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_60));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, empty_39bsv0yogVQhFyUP9bhXnyfwintsets)(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg* s) {
	NIM_BOOL result;
	nimfr_("empty", "intsets.nim");
	result = (NIM_BOOL)0;
	nimln_(352, "intsets.nim");
	result = ((*s).counter == ((NI) 0));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit000)(void) {
	nimfr_("intsets", "intsets.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit000)(void) {
static TNimNode* TM_ulJ2WYumkJwZ9b5Ewe7sCpg_14[3];
static TNimNode* TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[6];
static TNimNode TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[11];
NTI_ul49aWfv9aes8cutmeltT3gQ_.size = sizeof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ);
NTI_ul49aWfv9aes8cutmeltT3gQ_.kind = 18;
NTI_ul49aWfv9aes8cutmeltT3gQ_.base = 0;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_14[0] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[1];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[1].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[1].offset = offsetof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ, next);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[1].typ = (&NTI_Vz0pPzxitckVclPPWiz0xw_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[1].name = "next";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_14[1] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[2];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[2].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[2].offset = offsetof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ, key);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[2].name = "key";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_14[2] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[3];
NTI_9a8QARi5WsUggNU9bom7kzTQ_.size = sizeof(tyArray_9a8QARi5WsUggNU9bom7kzTQ);
NTI_9a8QARi5WsUggNU9bom7kzTQ_.kind = 16;
NTI_9a8QARi5WsUggNU9bom7kzTQ_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_9a8QARi5WsUggNU9bom7kzTQ_.flags = 3;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[3].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[3].offset = offsetof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ, bits);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[3].typ = (&NTI_9a8QARi5WsUggNU9bom7kzTQ_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[3].name = "bits";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[0].len = 3; TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[0].kind = 2; TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[0].sons = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_14[0];
NTI_ul49aWfv9aes8cutmeltT3gQ_.node = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[0];
NTI_Vz0pPzxitckVclPPWiz0xw_.size = sizeof(tyObject_Trunk_ul49aWfv9aes8cutmeltT3gQ*);
NTI_Vz0pPzxitckVclPPWiz0xw_.kind = 22;
NTI_Vz0pPzxitckVclPPWiz0xw_.base = (&NTI_ul49aWfv9aes8cutmeltT3gQ_);
NTI_Vz0pPzxitckVclPPWiz0xw_.marker = Marker_tyRef_Vz0pPzxitckVclPPWiz0xw;
NTI_9brg1xNurxcus33lU4IE1Dw_.size = sizeof(tySequence_9brg1xNurxcus33lU4IE1Dw*);
NTI_9brg1xNurxcus33lU4IE1Dw_.kind = 24;
NTI_9brg1xNurxcus33lU4IE1Dw_.base = (&NTI_Vz0pPzxitckVclPPWiz0xw_);
NTI_9brg1xNurxcus33lU4IE1Dw_.flags = 2;
NTI_9brg1xNurxcus33lU4IE1Dw_.marker = Marker_tySequence_9brg1xNurxcus33lU4IE1Dw;
NTI_PQrmFm4BXFkFSVOUl1ojSg_.size = sizeof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg);
NTI_PQrmFm4BXFkFSVOUl1ojSg_.kind = 18;
NTI_PQrmFm4BXFkFSVOUl1ojSg_.base = 0;
NTI_PQrmFm4BXFkFSVOUl1ojSg_.flags = 2;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[0] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[5];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[5].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[5].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, elems);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[5].name = "elems";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[1] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[6];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[6].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[6].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, counter);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[6].name = "counter";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[2] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[7];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[7].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[7].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, max);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[7].name = "max";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[3] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[8];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[8].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[8].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, head);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[8].typ = (&NTI_Vz0pPzxitckVclPPWiz0xw_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[8].name = "head";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[4] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[9];
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[9].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[9].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, data);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[9].typ = (&NTI_9brg1xNurxcus33lU4IE1Dw_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[9].name = "data";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[5] = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[10];
NTI_emiAJ8okywrJw7ZHLzlXbQ_.size = sizeof(tyArray_emiAJ8okywrJw7ZHLzlXbQ);
NTI_emiAJ8okywrJw7ZHLzlXbQ_.kind = 16;
NTI_emiAJ8okywrJw7ZHLzlXbQ_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_emiAJ8okywrJw7ZHLzlXbQ_.flags = 3;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[10].kind = 1;
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[10].offset = offsetof(tyObject_IntSet_PQrmFm4BXFkFSVOUl1ojSg, a);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[10].typ = (&NTI_emiAJ8okywrJw7ZHLzlXbQ_);
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[10].name = "a";
TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[4].len = 6; TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[4].kind = 2; TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[4].sons = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_33[0];
NTI_PQrmFm4BXFkFSVOUl1ojSg_.node = &TM_ulJ2WYumkJwZ9b5Ewe7sCpg_0[4];
}

